name: todo_project
description: "ToDo Project - A simple Flutter application to manage tasks"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  # shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  uuid: ^4.0.0
  provider: ^6.1.2
  path_provider: ^2.1.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
